dataCode: LPS_run1

sampleKey: "config/migasti_lps_sample_key.tsv"

interaction: True
interaction_name:
    - 'LPS'
    #- 'neutrophils_percent_z'
    #- 'visit_month'

num_pcs:
    - 0
    - 5
    - 10
    - 15
    - 20

countMatrixRData: "config/genes_tpm.rds"
metadataRData: "config/migasti_lps_metadata.tsv"

VCF: "/sc/arion/projects/als-omics/microglia_stimulated/genotypes/gsa_microglia_05-2021_allAncestry_MAF.vcf.gz"
GTF: "/sc/arion/projects/ad-omics/data/references//hg38_reference/GENCODE/gencode.v30.annotation.gtf.gz"

mode: "eQTL"

NUM_CHUNK: 100
